# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aleksey's Coursera Guided Projects
email: hackermaneia@riseup.net
description: > # this means to ignore newlines until "baseurl:"
  This is a portfolio for the Coursera Guided Projects that I managed to complete!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alekseyyycgp.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  alekseyyycgp

# Build settings
markdown: kramdown
